### ISSUE TITLE
Links to ZIP Files are dead

### ISSUE THREAD

**Issue by Kruno313** [microsoft/Windows-Camera#16]
Results in 404 Page Not Found

**Comment by Sudhaushu** [comment]
Works for me. Are you trying the link in the readme.md on the master branch?

**Comment by Kruno313** [comment]
It really works now.  Sorry for bothering You.
I was trying 3-4 times, also on different subprojects before I raised the issue. The last was Zip link in .md of the microsoft/Windows-Camera.
I use Chrome browser in Win7.
Thanks
