### ISSUE TITLE
Any question about VirtualCameraSimple project

### ISSUE THREAD

**Issue by 864171292juner** [microsoft/Windows-Camera#24]
When I use VirtualCameraSimple project, I compile according to README.md, but  I am prompted that I can't open the included file:“mfvirtualcamera.h”: No such file or directory. How do I get the mfvirtualcamera. h file?

  The link of install visual studio MSI project extension in Windows-Camera-master/Samples/VirtualCamera/README.md document is invalid.

  Looking forward to your reply.

**Comment by LPBourret** [comment]
> When I use VirtualCameraSimple project, I compile according to README.md, but I am prompted that I can't open the included file:“mfvirtualcamera.h”: No such file or directory. How do I get the mfvirtualcamera. h file?
> 
> The link of install visual studio MSI project extension in Windows-Camera-master/Samples/VirtualCamera/README.md document is invalid.
> 
> Looking forward to your reply.

Hi, until the announcement on June 24th of Windows 11. the required SDK was not released. Please see the [revised documentation](https://github.com/microsoft/Windows-Camera/tree/master/Samples/VirtualCamera) and links to download the appropriate Widnows 11 preview SDK that contains *mfvirtualcamera.h*

**Comment by 864171292juner** [comment]
> > When I use VirtualCameraSimple project, I compile according to README.md, but I am prompted that I can't open the included file:“mfvirtualcamera.h”: No such file or directory. How do I get the mfvirtualcamera. h file?
> > The link of install visual studio MSI project extension in Windows-Camera-master/Samples/VirtualCamera/README.md document is invalid.
> > Looking forward to your reply.
> 
> Hi, until the announcement on June 24th of Windows 11, the required SDK was not released. Please see the [revised documentation](https://github.com/microsoft/Windows-Camera/tree/master/Samples/VirtualCamera) and links to download the appropriate Windows 11 preview SDK that contains _mfvirtualcamera.h_

OK ,thanks
