### ISSUE TITLE
Unable to install Virtual Camera on Windows 10

### ISSUE THREAD

**Issue by AshwinRaikar88** [microsoft/Windows-Camera#26]
Is there a way to run this on Windows 10.....I've tried all possible setup instructions none of them are working even after deploying the app. 
I was able to build and run this app on Windows 11 but on Windows 10 I'm unable to wrap existing webcam devices

The error code is -2147024769 : The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)

**Comment by LPBourret** [comment]
take a look at this sample: [https://github.com/microsoft/Windows-driver-samples/tree/master/general/SimpleMediaSource](https://github.com/microsoft/Windows-driver-samples/tree/master/general/SimpleMediaSource)

**Comment by AshwinRaikar88** [comment]
@LPBourret Thanks
