### ISSUE TITLE
RPC failed error with the code 0x800706BE when calling IMFVirtualCamera::Start

### ISSUE THREAD

**Issue by ANEgorova** [microsoft/Windows-Camera#41]
Hello - I've been banging my head against the wall these past couple of weeks because I have no idea what I'm doing wrong. For some reason I get an RPC failed error with the code 0x800706BE when I try to start my Virtual Camera. My Virtual Camera is exactly the same as the SimpleMediaSource example from this repo, execpt it's in Rust.
There are two strange things to note:
    1. It used to work on pre-Windows 11 22H2 and stopped working after the update
    2. The c++ example works just fine.

Below are the logs callstack and some execptions that occur (from debugging with Windbg):

Callstack:
00 00000059`51afe288 00007ffb`c7b61bca     RPCRT4!NdrSendReceive+0x5
01 00000059`51afe290 00007ffb`c7b6104b     RPCRT4!NdrpClientCall3+0x6aa
02 00000059`51afe5b0 00007ffb`5c74a82c     RPCRT4!NdrClientCall3+0xeb
03 00000059`51afe940 00007ffb`5c70365d     FrameServerClient!FsClientImpl::AddDeviceToClient+0x5ec
04 00000059`51afebb0 00007ffb`5c702bc1     FrameServerClient!FsProxy::CreateStreamsForDevice+0x16d
05 00000059`51afee70 00007ffb`5c703ecc     FrameServerClient!FsProxy::CreateStreamsForAllDevices+0x2e1
06 00000059`51aff140 00007ffb`5c701bd7     FrameServerClient!FsProxy::Initialize+0x6ac
07 00000059`51aff210 00007ffb`5c7411db     FrameServerClient!FsProxy::CreateInstance+0x83
08 00000059`51aff250 00007ffb`5c7410ce     FrameServerClient!FSClientFactory::CreateInstanceByService+0xab
09 00000059`51aff2b0 00007ffb`bae2f094     FrameServerClient!FSClientFactory::CreateInstance+0x8e
0a 00000059`51aff2f0 00007ffb`5c7b4ecf     MFCORE!MFCreateDeviceSource+0x574
0b 00000059`51aff410 00007ffb`5c7b88e5     FrameServerMonitorClient!FSMSessionVirtualCamera::InternalEnableCamera+0x71f
0c 00000059`51aff590 00007ff6`c1f34540     FrameServerMonitorClient!FSMSessionVirtualCamera::Start+0x45
0d 00000059`51aff5c0 00007ff6`c1f32928     vcam!windows::Windows::Win32::Media::MediaFoundation::IMFVirtualCamera::Start<enum$<core::option::Option<ref$<windows::Windows::Win32::Media::MediaFoundation::IMFAsyncCallback> >, 1, 18446744073709551615, Some> >+0xb0 [C:\Users\Brian\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.39.0\src\Windows\Win32\Media\MediaFoundation\mod.rs @ 46663] 
0e 00000059`51aff680 00007ff6`c1f320ab     vcam!vcam::main+0x3d8 [C:\Users\Brian\Documents\source\vcam\vcam\src\main.rs @ 45] 
0f 00000059`51affaa0 00007ff6`c1f352bb     vcam!core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs @ 227] 
10 00000059`51affae0 00007ff6`c1f34fd1     vcam!std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >+0x1b [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\sys_common\backtrace.rs @ 125] 
11 00000059`51affb20 00007ff6`c1f4150e     vcam!std::rt::lang_start::closure$0<tuple$<> >+0x11 [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\rt.rs @ 145] 
12 (Inline Function) --------`--------     vcam!core::ops::function::impls::impl$2::call_once+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs @ 259] 
13 (Inline Function) --------`--------     vcam!std::panicking::try::do_call+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs @ 492] 
14 (Inline Function) --------`--------     vcam!std::panicking::try+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs @ 456] 
15 (Inline Function) --------`--------     vcam!std::panic::catch_unwind+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs @ 137] 
16 (Inline Function) --------`--------     vcam!std::rt::lang_start_internal::closure$2+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs @ 128] 
17 (Inline Function) --------`--------     vcam!std::panicking::try::do_call+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs @ 492] 
18 (Inline Function) --------`--------     vcam!std::panicking::try+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs @ 456] 
19 (Inline Function) --------`--------     vcam!std::panic::catch_unwind+0xb [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs @ 137] 
1a 00000059`51affb60 00007ff6`c1f34f9f     vcam!std::rt::lang_start_internal+0x13e [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs @ 128] 
1b 00000059`51affc50 00007ff6`c1f32bd6     vcam!std::rt::lang_start<tuple$<> >+0x2f [/rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\rt.rs @ 144] 
1c 00000059`51affcb0 00007ff6`c1f5abbc     vcam!main+0x16
1d (Inline Function) --------`--------     vcam!invoke_main+0x22 [d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
1e 00000059`51affce0 00007ffb`c660244d     vcam!__scrt_common_main_seh+0x10c [d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
1f 00000059`51affd20 00007ffb`c848df78     KERNEL32!BaseThreadInitThunk+0x1d
20 00000059`51affd50 00000000`00000000     ntdll!RtlUserThreadStart+0x28

RPC exceptions:
(39ac.2488): Unknown exception - code 000006be (first chance)
(39ac.2488): Unknown exception - code 000006bf (first chance)
(39ac.2488): Unknown exception - code 000006bf (first chance)

Logs:
successfully created camera!
Called: <vcam_media_source::vcam_media_source_activate_factory::VCamMediaSourceActivateFactory as windows::Windows::Win32::System::Com::IClassFactory_Impl>::CreateInstance
Called: vcam_media_source::vcam_media_source_activate::VCamMediaSourceActivate::new
Called: <vcam_media_source::vcam_media_source_activate::VCamMediaSourceActivate as windows::Windows::Win32::Media::MediaFoundation::IMFAttributes_Impl>::GetItemType
Called: <vcam_media_source::vcam_media_source_activate::VCamMediaSourceActivate as windows::Windows::Win32::Media::MediaFoundation::IMFAttributes_Impl>::SetItem
Called: <vcam_media_source::vcam_media_source_activate::VCamMediaSourceActivate as windows::Windows::Win32::Media::MediaFoundation::IMFAttributes_Impl>::GetUINT32
Called: <vcam_media_source::vcam_media_source_activate::VCamMediaSourceActivate as windows::Windows::Win32::Media::MediaFoundation::IMFActivate_Impl>::ActivateObject
Called: vcam_media_source::vcam_media_source::VCamMediaSource::new
Called: vcam_media_source::vcam_media_source::VCamMediaSource::create_attributes
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::new
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::set_stream_attributes
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::set_stream_attributes
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::init_mft
Called: <vcam_media_source::vcam_media_stream::VCamMediaStream as windows::Windows::Win32::Media::MediaFoundation::IMFMediaStream_Impl>::GetStreamDescriptor
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::check_shutdown
Called: <vcam_media_source::vcam_media_source::VCamMediaSource as windows::Windows::Win32::Media::MediaFoundation::IMFMediaSourceEx_Impl>::GetSourceAttributes
Called: vcam_media_source::vcam_media_source::VCamMediaSource::check_shutdown
Called: <vcam_media_source::vcam_media_source::VCamMediaSource as windows::Windows::Win32::Media::MediaFoundation::IMFGetService_Impl>::GetService
Called: vcam_media_source::vcam_media_source::VCamMediaSource::check_shutdown
Called: <vcam_media_source::vcam_media_source::VCamMediaSource as windows::Windows::Win32::Media::MediaFoundation::IMFMediaSource_Impl>::CreatePresentationDescriptor
Called: vcam_media_source::vcam_media_source::VCamMediaSource::check_shutdown
Called: <vcam_media_source::vcam_media_source::VCamMediaSource as windows::Windows::Win32::Media::MediaFoundation::IMFMediaSourceEx_Impl>::GetStreamAttributes
Called: vcam_media_source::vcam_media_source::VCamMediaSource::check_shutdown
Called: vcam_media_source::vcam_media_source::VCamMediaSource::get_media_stream_by_id
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::get_id
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::get_attributes
Called: <vcam_media_source::vcam_media_source::VCamMediaSource as windows::Windows::Win32::Media::MediaFoundation::IMFMediaSourceEx_Impl>::GetSourceAttributes
Called: vcam_media_source::vcam_media_source::VCamMediaSource::check_shutdown
Called: <vcam_media_source::vcam_media_source::VCamMediaSource as windows::Windows::Win32::Media::MediaFoundation::IMFMediaSourceEx_Impl>::GetSourceAttributes
Called: vcam_media_source::vcam_media_source::VCamMediaSource::check_shutdown
Called: <vcam_media_source::vcam_media_source::VCamMediaSource as windows::Windows::Win32::Media::MediaFoundation::IMFMediaSource_Impl>::Shutdown
Called: vcam_media_source::vcam_media_stream::VCamMediaStream::shutdown
thread 'main' panicked at 'failed to start camera: Error { code: 0x800706BE, message: The remote procedure call failed. }', vcam\src\main.rs:45:36

**Comment by kasumman** [comment]
Hi,
That RPC error typically means that the other end is crashing, can you observe if FrameServer service is suddenly crashing (Task Manager services tab)?
Can you also attach a trace from the repro case: please see https://github.com/Microsoft/busiotools/tree/master/camera/Tracing

**Comment by kasumman** [comment]
Closing as no further activity on this.

**Comment by kasumman** [comment]
Closing as no further activity on this.
