### ISSUE TITLE
Win 11 22H2 has QR Code Reader

### ISSUE THREAD

**Issue by simplythomasjay** [microsoft/Windows-Camera#42]
The Windows Camera version 2022.2206.2.0 has a QR-Code Reading Feature.

[https://www.howtogeek.com/818230/windows-11-is-getting-a-built-in-qr-code-scanner/](url)

With devices that already has Win 11 22H2 installed it is possible to use the built-in camera for QR-Code reading.

This is a no-brainer on Android or iPhone devices but constantly P.I.T.A. on Windows devices.

Is it possible to integrate a QR-Code-reading-sample into this project?

**Comment by LPBourret** [comment]
Hi,
there are code samples for camera-based barcode (and QR code) reader: https://github.com/microsoft/windows-universal-samples/tree/main/Samples/BarcodeScanner
