### ISSUE TITLE
Can't get DefaultController when turning on the MEP Automatic Framing

### ISSUE THREAD

**Issue by LiangJy123** [microsoft/Windows-Camera#48]
Hi ,
I'm trying to get  ***DefaultController*** to turn on or off mep features (Blur , Eye Contact , Automatic Framing).
I found a strange issue, that When  turning on the Automatic Framing , I will get a exception: 
```C#
Unspecified error

 

D:\github\Windows-Camera\Samples\CameraSettingsExternalSettingsApp\DefaultControlHelper\DefaultControlHelper.cpp(104)\DefaultControlHelper_WinRT.dll!00007FFA753EFA8C: (caller: 00007FFA753E3049) Exception(1) tid(1350) 8007000D The data is invalid.
    [winrt::DefaultControlHelper::implementation::DefaultController::DefaultController(existingControlDefaults->UnlockControlData())]
```

Can you double confirm that ?

Thanks

**Comment by LiangJy123** [comment]
Hi Kasumman,
Thanks for helping.
1.UWP 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/13048899/227407469-98086849-dc21-4e61-b63e-1fce1e2edfbe.png">
2.UWP DLL
<img width="593" alt="image" src="https://user-images.githubusercontent.com/13048899/227407612-07194cbd-d879-4b9e-aec7-a6d0c8c4a8af.png">
3.OS Version 
22H2 OS Build 22621.963

Thanks.

**Comment by kasumman** [comment]
I think this might be a known issue that is fixed in Windows Insider builds.

Does the sample app work if you first reset the settings from the Camera Settings?
1. Open Camera Settigns, click "Reset Settings" button
2. Open the associated external settings app and try to use your auto framing code addition?

**Comment by LiangJy123** [comment]
@kasumman  Thanks a lot!
It works when I reset the camera at setting page.
