### ISSUE TITLE
How to register the VirtualCameraMediaSource DLL without the MSI?

### ISSUE THREAD

**Issue by gabriel-lando** [microsoft/Windows-Camera#51]
I'm trying to register the VirtualCameraMediaSource.dll without using the MSI installer.

Using the MSI, the sample worked very well, but I don't want to use this installer.
I tried to call the `regsvr32.exe` to register the DLL, but it failed.
Also, based on the README, I tried to add the registry entries manually and it didn't work too.

I created a .reg file exporting the registry entries created by the installer and changed the DLL path to a different path and it also didn't work.

This is my .reg file:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{7B89B92E-FE71-42D0-8A41-E137D06EA184}]
@="VirtualCameraMediaSource"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{7B89B92E-FE71-42D0-8A41-E137D06EA184}\InProcServer32]
"ThreadingModel"="Both"
@=""C:\\VirtualCamera\\VirtualCameraMediaSource.dll""
```

After adding these registry entries, the DLL isn't being loaded. I really don't know the difference between adding from the MSI and manually.

Anyone know how to do it without the MSI? Thanks :)

**Comment by kasumman** [comment]
Hi,
I think following is needed, allow "LOCAL SERVICE" to read & execute the c:\VirtualCamera folder and its content as as this dll is loaded by a Windows service that's running as "LOCAL SERVICE" account. This can be done by right clicking the folder/file -> properties ->security tab -> Edit -> add

Let us know if this works, thanks.

**Comment by gabriel-lando** [comment]
It still doesn't work :(

Before that, I tried to add "everyone" with full control.

I also replaced the child object permissions, so the file has the same permissions:

![image](https://github.com/microsoft/Windows-Camera/assets/18423120/d86091c7-0ce2-4bff-a7df-5b54d07d7814)
![image](https://github.com/microsoft/Windows-Camera/assets/18423120/c8f488f2-8ad9-4171-bcdd-d9b7fe81df82)

**Comment by gabriel-lando** [comment]
Ohhh it was my mistake :( I created the .reg file with some extra quotes :( I noticed that after removing the extra quotes in the regedit, it worked:

![image](https://github.com/microsoft/Windows-Camera/assets/18423120/e43e2133-e0ea-4c6e-8f7c-e5379ebd7a42)

Sorry about that, I missed an entire day on it :D

**Comment by BingoZha** [comment]
> Ohhh it was my mistake :( I created the .reg file with some extra quotes :( I noticed that after removing the extra quotes in the regedit, it worked:
> 
> ![image](https://user-images.githubusercontent.com/18423120/256325940-e43e2133-e0ea-4c6e-8f7c-e5379ebd7a42.png)
> 
> Sorry about that, I missed an entire day on it :D

Can you see the virtual camera name in obs after register?

**Comment by gabriel-lando** [comment]
> Can you see the virtual camera name in obs after register?

Yes, but after registering the DLL, you need to create at least one virtual camera. To do it, you can run the UWP application that is part of this solution. In the app, you can create one or more virtual cameras, with the name you want. Then, OBS will list all cameras.

OBS: after registering the DLL, it is important to restart the FrameServer service (it usually stops after some minutes of inactivity, so it shouldn't be a problem, unless you are using another camera)

**Comment by BingoZha** [comment]
> > Can you see the virtual camera name in obs after register?
> 
> Yes, but after registering the DLL, you need to create at least one virtual camera. To do it, you can run the UWP application that is part of this solution. In the app, you can create one or more virtual cameras, with the name you want. Then, OBS will list all cameras.
> 
> OBS: after registering the DLL, it is important to restart the FrameServer service (it usually stops after some minutes of inactivity, so it shouldn't be a problem, unless you are using another camera)

OK,Thank you
