### ISSUE TITLE
How to run the example NetworkMediaStreamer?

### ISSUE THREAD

**Issue by Xbathy** [microsoft/Windows-Camera#52]
<img width="1179" alt="image" src="https://github.com/microsoft/Windows-Camera/assets/63304916/a8e1e6f6-5592-4844-8289-15881c951545">
Will stuck here.
How to run this example, thanks!

**Comment by Xbathy** [comment]
![image](https://github.com/microsoft/Windows-Camera/assets/63304916/798c1c41-67d4-492c-a7dc-538888388879)
And 305 line can't reach,  there is problem in AddUser()

**Comment by Sudhaushu** [comment]
Hi, can you provide a little bit more information.
Which OS version and SDK are you using for the build? 
Are you building with DISABLE_SECURE_RTSP flag?  
The AddUser simply uses keyVault API to store username and password combination. I do not foresee any blocking calls there.
Are you experiencing that the process is crashing? 
Did you also try running the Server in admin mode?

**Comment by Xbathy** [comment]
this is the SDK. ![image](https://github.com/microsoft/Windows-Camera/assets/63304916/d525b44c-61c3-4aa4-9a1f-f8ab6b6fe6bc)
 I don't set flag DISABLE_SECURE_RTSP.
I hava try try to play the exe admin mode , but same..

**Comment by Xbathy** [comment]
there is the logs

'CameraRTPStreamerApp.exe' (Win32): Loaded 'E:\Projects\Windows-Camera\Samples\NetworkMediaStreamer\x64\Release\CameraRTPStreamerApp.exe'. Symbols loaded.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfplat.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'E:\Projects\Windows-Camera\Samples\NetworkMediaStreamer\x64\Release\RTPMediaStreamer.dll'. Symbols loaded.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'E:\Projects\Windows-Camera\Samples\NetworkMediaStreamer\x64\Release\RTSPServer.dll'. Symbols loaded.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mf.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\secur32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfcore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\RTWorkQ.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
The thread 0xff38 has exited with code 0 (0x0).
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Media.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Devices.Enumeration.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\StructuredQuery.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\MSWB70804.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\NL7Data0804.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DevDispItemProvider.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DDORes.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DefaultDeviceManager.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\directxdatabasehelper.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\nvldumdx.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cryptnet.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\drvstore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\nvwgf2umx.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
The thread 0x11298 has exited with code 0 (0x0).
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\NvCamera\NvCameraAllowlisting64.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\NvCamera\NvCameraAllowlisting64.dll'
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\nvspcap64.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\MFCaptureEngine.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CompPkgSup.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.ApplicationModel.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\FrameServerClient.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfsensorgroup.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\AppXDeploymentClient.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Media.MediaControl.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfreadwrite.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\AudioSes.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CoreMmRes.dll'. Module was built without symbols.
'CameraRTPStreamerApp.exe' (Win32): Unloaded 'C:\Windows\System32\CoreMmRes.dll'
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CoreMmRes.dll'. Module was built without symbols.
Exception thrown at 0x00007FFDFF7E536C (KernelBase.dll) in CameraRTPStreamerApp.exe: WinRT originate error - 0xC00DABE0 : '没有可用的捕获设备。'.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CryptoWinRT.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\vaultcli.dll'. 
The thread 0x9c30 has exited with code 0 (0x0).
The thread 0xca4 has exited with code 0 (0x0).

**Comment by Xbathy** [comment]
Now will crash after update system ，
'CameraRTPStreamerApp.exe' (Win32): Loaded 'E:\Projects\Windows-Camera\Samples\NetworkMediaStreamer\x64\Release\CameraRTPStreamerApp.exe'. Symbols loaded.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfplat.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'E:\Projects\Windows-Camera\Samples\NetworkMediaStreamer\x64\Release\RTPMediaStreamer.dll'. Symbols loaded.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'E:\Projects\Windows-Camera\Samples\NetworkMediaStreamer\x64\Release\RTSPServer.dll'. Symbols loaded.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mf.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\secur32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfcore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\RTWorkQ.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
The thread 0x7cdc has exited with code 0 (0x0).
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Media.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Devices.Enumeration.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\StructuredQuery.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\MSWB70804.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\NL7Data0804.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DevDispItemProvider.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DDORes.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DefaultDeviceManager.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\directxdatabasehelper.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\nvldumdx.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cryptnet.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\drvstore.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\nvwgf2umx.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\NvCamera\NvCameraAllowlisting64.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_7947c31fc944635c\NvCamera\NvCameraAllowlisting64.dll'
The thread 0x6170 has exited with code 0 (0x0).
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\nvspcap64.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\MFCaptureEngine.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CompPkgSup.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.ApplicationModel.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\AppXDeploymentClient.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\FrameServerClient.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfsensorgroup.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Media.MediaControl.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\mfreadwrite.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\AudioSes.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CoreMmRes.dll'. Module was built without symbols.
'CameraRTPStreamerApp.exe' (Win32): Unloaded 'C:\Windows\System32\CoreMmRes.dll'
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CoreMmRes.dll'. Module was built without symbols.
Exception thrown at 0x00007FFDE357531C (KernelBase.dll) in CameraRTPStreamerApp.exe: WinRT originate error - 0xC00DABE0 : '没有可用的捕获设备。'.
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\CryptoWinRT.dll'. 
'CameraRTPStreamerApp.exe' (Win32): Loaded 'C:\Windows\System32\vaultcli.dll'. 
Exception thrown at 0x00007FFDE357531C (KernelBase.dll) in CameraRTPStreamerApp.exe: WinRT originate error - 0x8009030E : '安全包中没有可用的凭证'.
Exception thrown at 0x00007FFDE357531C in CameraRTPStreamerApp.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x00000090E60FF740.
