### ISSUE TITLE
How to send a frame into virtual camera?

### ISSUE THREAD

**Issue by BingoZha** [microsoft/Windows-Camera#53]
I have an external c++ application, if it needs to write a frame into virtual camera, what function can i use? KsProperty?

**Comment by roman380** [comment]
Virtual camera API does not cover video frame injection, you are supposed to deal with this yourselves, that is arrange transfer of data from the external app into media source working in the context of frame server serivce.

**Comment by LPBourret** [comment]
Hi, yep indeed this kind of scenario is not something we highlight, you could send frames to the vcam (i.e. via a custom DDI, I would advise you batch them to minimize the amount of DDI calls) from your app to be then streamed by the vcam. In this mode of operation though, you would probably want to tie the vcam lifetime to the lifetime of the frame-providing app.
