### ISSUE TITLE
Autoframing can't be set to DIGITALWINDOW_MANUAL with error status = 3(value is invalid)

### ISSUE THREAD

**Issue by LiangJy123** [microsoft/Windows-Camera#57]
Hi ,

I find this question on ***23H2 (build 22631.2715)***
And it seems only happened on Intel platform.

The ETL log shows that the flag set to digitalwindow is 2.
 
Can you comfirm that is a bug or other situations?

Thank you!

**Comment by LPBourret** [comment]
Hi, KSCAMERA_EXTENDEDPROP_DIGITALWINDOW_MANUAL (0) and KSCAMERA_EXTENDEDPROP_DIGITALWINDOW_AUTOFACEFRAMING (1) are the only values defined in the specification for this DDI (https://learn.microsoft.com/en-us/windows-hardware/drivers/stream/ksproperty-cameracontrol-extended-digitalwindow) this value indeed seems unexpected.

**Comment by LiangJy123** [comment]
Thank you for reply.
I have no idea about the flag tried to be set as 2 when I saw the log . 
I will report this issues again when there are more further OS version or machine platform trigger it.

**Comment by kasumman** [comment]
Just adding a note that it's not mixed to KSPROPERTY Flags field where 2 equals KSPROPERTY_TYPE_SET

**Comment by LiangJy123** [comment]
To set  DIGITALWINDOW_MANUAL , we also need to add setting payload with ***KSCAMERA_EXTENDEDPROP_DIGITALWINDOW_SETTING*** 

![image](https://github.com/microsoft/Windows-Camera/assets/13048899/ed85d277-601b-4511-a78e-e55596db2427)

That's why the interface returned 3 (indicating the value is invalid).
