### ISSUE TITLE
Appending Image to Source

### ISSUE THREAD

**Issue by r2997790** [microsoft/Windows-Camera#61]
Hey there,

Is it possible to append to the source, ie. the live system camera → pointed at the virtual camera (and then appending to the source a watermark), so the virtual camera output is:

Source 1 (live cam) + Source 2 (watermark) = Virtual Camera output

Many thanks
R

**Comment by roman380** [comment]
This is possible, but it's not the appendage. 

You implement your own virtual camera. Then as a part of its operation you capture video frames from real camera, post-process them and deliver as originating from your camera. This is how you introduce the watermark.
