### ISSUE TITLE
Windows Studio sample application thrown error while enabling the Automatic Framing

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/Windows-Camera#71]
We have encountered an issue while trying to enable the Automatic Framing feature through the windows studio sample application.
While debugging the code observed new **control code 21** in the function **CameraControlMonitor_ControlChanged** 

            switch (control.controlId)
            {
                case (uint)ExtendedControlKind.KSPROPERTY_CAMERACONTROL_EXTENDED_EYEGAZECORRECTION:
                    m_uiDispatcherQueue.TryEnqueue(DispatcherQueuePriority.Normal, () => RefreshEyeGazeUI());
                    break;

                case (uint)ExtendedControlKind.KSPROPERTY_CAMERACONTROL_EXTENDED_BACKGROUNDSEGMENTATION:
                    m_uiDispatcherQueue.TryEnqueue(DispatcherQueuePriority.Normal, () => RefreshBackgroundSegmentationUI());
                    break;

                case (uint)ExtendedControlKind.KSPROPERTY_CAMERACONTROL_EXTENDED_DIGITALWINDOW:
                    m_uiDispatcherQueue.TryEnqueue(DispatcherQueuePriority.Normal, () => RefreshAutomaticFramingUI());
                    break;

                default:
                    throw new Exception("unhandled control change, implement or allow through at your convenience");
                    break;
            }

Along with the Automatic framing toggling observed following control ids

Debug Log:
KSPROPERTY_CAMERACONTROL_EXTENDED_DIGITALWINDOW changed externally
21 changed externally
22 changed externally
24 changed externally
15 changed externally
KSPROPERTY_CAMERACONTROL_EXTENDED_DIGITALWINDOW changed externally
21 changed externally
22 changed externally
24 changed externally
15 changed externally
The thread '[Thread Destroyed]' (7000) has exited with code 0 (0x0).
KSPROPERTY_CAMERACONTROL_EXTENDED_DIGITALWINDOW changed externally
21 changed externally
22 changed externally
24 changed externally
15 changed externally
The thread '[Thread Destroyed]' (1740) has exited with code 0 (0x0).

Note: Just have commented the above exception and tried executing the application and shared the above debug logs

![Image](https://github.com/user-attachments/assets/a48db489-06b7-44eb-9629-b2642af1198a)

**Comment by LPBourret** [comment]
Hi,
yes the exception code tells you that if you wish to intercept change to another control or allow it through (meaning not throw an exception) then you can change the code accordingly, such as like you did by commenting it.
Alternatively, you can change the content of the variable named *controlDataToMonitor* (https://github.com/microsoft/Windows-Camera/blob/051a609a2699e4d67097700b3920509745b2c30d/Samples/WindowsStudio/WindowsStudioSample_WinUI/MainWindow.xaml.cs#L231) so that it only subscribes to control changes you want to monitor instead of "all of them".

**Comment by pbvinoth** [comment]
Thank you Bourret for the info.
