### ISSUE TITLE
What cameras are windows compliant 360-degree cameras?

### ISSUE THREAD

**Issue by jasonhbartlett** [microsoft/Windows-Camera#8]
How do know what cameras/webcams are windows compliant 360-degree cameras?  Is there a list somewhere?
When I tested this on my Dell Alienware R17 laptop it could detect the Integrated Webcam.  It also detected the cameras built into the Samsung Odyssey HMD.  I also worked with the Logitech C920 external webcam.  It did NOT work with my Ricoh Theta V 360 camera.  (the only 360 camera I have)

The problem with this camera I found in debugging the program was in the check for:
```csharp
sourceInfo.SourceKind == MediaFrameSourceKind.Color  // (MainPage.xaml.cs Line#501)
```
 where my Ricoh Theta V was reporting as 
```csharp
MediaFrameSourceKind.Custom
```
 and thus not compliant?

Is this something I can tweak the app to get working with the Ricoh Theta V, or do I need to hope that Ricoh will update the driver?

And is there a list of complaint camera's somewhere?
@Sudhaushu @LPBourret

**Comment by LPBourret** [comment]
no such list exist today, it is up to manufacturer to adhere to the 360 camera standards from their drivers. Indeed they would register a color camera with proper attribute that identify the stream as a supported spherical projection such as equirectangular
